apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yqdl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-yqdl@sha256:2c71a79ebdc0bd5706d19bc4b6736ef9eec5869b7af78a9e81039cb1dac87ebe
        name: my-nodejs
        resources: {}
status: {}
